### PR TITLE
Add Twente Colormap

### PR DESCRIPTION
**Pull request by Steven9101**
Fixes the gain (reduces the factor so it doesnt distort and sounds fine). Also sets a default gain in audio.js

### CODE REVIEW

**Comment by Steven9101** [comment]
Probably not the main fix because the AGC will also amplify but atleast it doesnt hurt the ears now.

**Comment by rhgndf** [comment]
Just to check, did you come up with the websdr colormap yourself?

**Comment by Steven9101** [comment]
Yes, the websdr colormap was made by myself. I just like the websdr colormap as it looks clean and has nice colors.

**Comment by Steven9101** [comment]
I mean yes, its not the original to 100% but its extremly near to it.

**Comment by Steven9101** [comment]
Now only the twente colormap is needed.

**Pull request merged**
